# Use postgres/example user/password credentials

volumes:
  database-data:
  redis-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/
    env_file: .env
    networks:
      - stack

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - stack
    ports:
      - "${REDIS_PORT:-6379}:6379"

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - stack
    ports:
      - 8765:3000
    env_file: .env
    environment:
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXT_PUBLIC_API_V2_URL=${NEXT_PUBLIC_API_V2_URL}
      - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
      - NEXT_PUBLIC_WEBSITE_TERMS_URL=${NEXT_PUBLIC_WEBSITE_TERMS_URL}
      - NEXT_PUBLIC_WEBSITE_PRIVACY_POLICY_URL=${NEXT_PUBLIC_WEBSITE_PRIVACY_POLICY_URL}
      - NEXT_PUBLIC_SINGLE_ORG_SLUG=${NEXT_PUBLIC_SINGLE_ORG_SLUG}
      - ORGANIZATIONS_ENABLED=${ORGANIZATIONS_ENABLED}
      - CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_DIRECT_URL=${DATABASE_URL}
      - CSP_POLICY=${CSP_POLICY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - database



